### ISSUE TITLE
"ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents" on some devices

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#100]
```
java.lang.RuntimeException: Unable to start receiver com.vaguehope.onosendai.update.AlarmReceiver: android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2126)
at android.app.ActivityThread.access$1500(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:118)
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:112)
at com.vaguehope.onosendai.update.AlarmReceiver.onReceive(AlarmReceiver.java:31)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2119)
... 10 more
android.content.ReceiverCallNotAllowedException: IntentReceiver components are not allowed to register to receive intents
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:118)
at android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:112)
at com.vaguehope.onosendai.update.AlarmReceiver.onReceive(AlarmReceiver.java:31)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2119)
at android.app.ActivityThread.access$1500(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1197)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by phtan** [comment]
This issue was mentioned in an academic paper. It appears in the section 'iii. approach detail' in the paper 'Fixing Recurring Crash Bugs via Analyzing Q&A Sites', which was written by Gao et al. I retrieved the paper from the following URL: [http://sei.pku.edu.cn/~zhanglu/Download/ASE15-Gao.pdf](http://sei.pku.edu.cn/~zhanglu/Download/ASE15-Gao.pdf)
