### ISSUE TITLE
Need to clear webview cache after Twitter oauth

### ISSUE THREAD

**Issue by haku** [haku/Onosendai#160]

**Comment by haku** [comment]
Also:
```
E/onosendai( 5411): TOW Failed to init OAuth.
E/onosendai( 5411): java.lang.IllegalStateException: Access token already available.
E/onosendai( 5411):     at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:103)
E/onosendai( 5411):     at twitter4j.auth.OAuthAuthorization.getOAuthRequestToken(OAuthAuthorization.java:92)
E/onosendai( 5411):     at twitter4j.TwitterBaseImpl.getOAuthRequestToken(TwitterBaseImpl.java:263)
E/onosendai( 5411):     at com.vaguehope.onosendai.ui.pref.TwitterOauthWizard$TwitterOauthInitTask.doInBackground(TwitterOauthWizard.java:124)
E/onosendai( 5411):     at com.vaguehope.onosendai.ui.pref.TwitterOauthWizard$TwitterOauthInitTask.doInBackground(TwitterOauthWizard.java:105)
E/onosendai( 5411):     at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/onosendai( 5411):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/onosendai( 5411):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/onosendai( 5411):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/onosendai( 5411):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/onosendai( 5411):     at java.lang.Thread.run(Thread.java:818)

```

**Comment by haku** [comment]
Seems good.
Closing.
